upstream php-upstream {
    server app:9000;
}

server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    # 🔥 TAMBAHKAN INI
    client_max_body_size 500M;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        #fastcgi_param HTTPS on;
        #fastcgi_param HTTP_X_FORWARDED_PROTO https;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
    }


    location ~ /\.ht {
        deny all;
    }
}
